export const BRAND_COLOR = 0x74D7EC;

export interface DiscussionPrompt {
  category: string;
  text: string;
  reactions: string[];
}

export const DISCUSSION_CATEGORIES: Record<string, { label: string; description: string }> = {
  technique: { label: 'Technique', description: 'Composition, exposure, lighting, post-processing' },
  gear: { label: 'Gear', description: 'Lenses, cameras, accessories, workflow tools' },
  creative: { label: 'Creative Process', description: 'Inspiration, artistic voice, creative blocks' },
  challenge: { label: 'Challenge', description: 'Photo assignments and creative constraints' },
  inspiration: { label: 'Inspiration', description: 'Other art forms, artists, cross-discipline ideas' },
};

export const DISCUSSION_PROMPTS: DiscussionPrompt[] = [
  // --- technique (12) ---
  { category: 'technique', text: "What's a composition rule you intentionally break, and what made you start?", reactions: ['📐', '🎯', '💡'] },
  { category: 'technique', text: 'How do you decide between shooting wide open vs. stopped down for a portrait?', reactions: ['📸', '🔍', '🤔'] },
  { category: 'technique', text: 'What is your go-to approach for handling harsh midday light?', reactions: ['☀️', '🌤️', '💡'] },
  { category: 'technique', text: "Share a photo where you nailed the exposure in a tricky situation — what was your metering strategy?", reactions: ['🎯', '📊', '🔥'] },
  { category: 'technique', text: 'Do you prefer to get it right in camera or fix it in post? Where do you draw the line?', reactions: ['📷', '🖥️', '⚖️'] },
  { category: 'technique', text: 'What is the most underrated post-processing technique you use regularly?', reactions: ['🖥️', '✨', '💎'] },
  { category: 'technique', text: "How do you approach focus stacking for landscape shots? Any tips for beginners?", reactions: ['🏔️', '🔍', '📚'] },
  { category: 'technique', text: "What's the biggest mistake you see beginners make with white balance?", reactions: ['🎨', '🌡️', '📝'] },
  { category: 'technique', text: 'When do you choose black and white over color, and what drives that decision?', reactions: ['⬛', '⬜', '🎭'] },
  { category: 'technique', text: 'How has your editing style evolved over the past year?', reactions: ['📈', '🖌️', '🔄'] },
  { category: 'technique', text: "What's one technique you struggled with but finally mastered? How did it click?", reactions: ['💪', '💡', '🎉'] },
  { category: 'technique', text: 'Do you shoot bracketed exposures often? When is it worth the effort?', reactions: ['📊', '🌅', '🤷'] },
  { category: 'technique', text: 'What is your favorite way to use leading lines in a composition?', reactions: ['📐', '👁️', '🛤️'] },
  { category: 'technique', text: 'How do you meter for scenes with extreme dynamic range?', reactions: ['📊', '🌅', '🔧'] },
  { category: 'technique', text: 'What is your approach to color grading — do you follow a formula or go by feel?', reactions: ['🎨', '🖥️', '🤔'] },
  { category: 'technique', text: 'How do you handle chromatic aberration in your workflow?', reactions: ['🔍', '🌈', '🔧'] },
  { category: 'technique', text: 'What is the most creative use of depth of field you have seen or tried?', reactions: ['🔍', '🎨', '💡'] },
  { category: 'technique', text: 'Do you use the histogram while shooting or only in post? How does it help?', reactions: ['📊', '📸', '💡'] },
  { category: 'technique', text: 'How do you decide between center-weighted, spot, and matrix metering?', reactions: ['🎯', '📊', '🤔'] },
  { category: 'technique', text: 'What is your technique for getting tack-sharp eyes in portraits?', reactions: ['👁️', '🎯', '📸'] },
  { category: 'technique', text: 'How do you use negative space effectively in your compositions?', reactions: ['⬜', '🖼️', '🎨'] },
  { category: 'technique', text: 'What is your approach to shooting in fog or mist for atmosphere?', reactions: ['🌫️', '🎭', '📸'] },
  { category: 'technique', text: 'How do you avoid and correct lens distortion in architectural photography?', reactions: ['🏛️', '📐', '🔧'] },
  { category: 'technique', text: 'What is your preferred method for achieving smooth bokeh backgrounds?', reactions: ['✨', '🔍', '📸'] },
  { category: 'technique', text: 'How do you shoot handheld in low light without excessive noise?', reactions: ['🌙', '🖐️', '📸'] },
  { category: 'technique', text: 'What is the trickiest white balance scenario you have dealt with, and how did you solve it?', reactions: ['🌡️', '🎨', '💡'] },
  { category: 'technique', text: 'Do you use back-button focus? What made you switch (or not)?', reactions: ['🔘', '🎯', '🤔'] },
  { category: 'technique', text: 'How do you approach panorama stitching — any tips for seamless results?', reactions: ['🏔️', '🔗', '📸'] },
  { category: 'technique', text: 'What is your strategy for shooting silhouettes that look intentional, not accidental?', reactions: ['🌅', '🎭', '📸'] },
  { category: 'technique', text: 'How do you use fill flash outdoors without making it look artificial?', reactions: ['⚡', '☀️', '⚖️'] },
  { category: 'technique', text: 'What is your process for culling photos after a big shoot?', reactions: ['🗂️', '✂️', '⏱️'] },
  { category: 'technique', text: 'How do you approach long exposure photography for water or clouds?', reactions: ['🌊', '☁️', '⏱️'] },
  { category: 'technique', text: 'What is your go-to crop ratio and why?', reactions: ['📐', '🖼️', '🤔'] },
  { category: 'technique', text: 'How do you use color theory to make your photos more impactful?', reactions: ['🎨', '🔴', '💡'] },
  { category: 'technique', text: 'What is the most useful keyboard shortcut in your editing software?', reactions: ['⌨️', '🚀', '💡'] },
  { category: 'technique', text: 'How do you photograph reflections — water, glass, mirrors — to best effect?', reactions: ['🪞', '🌊', '📸'] },
  { category: 'technique', text: 'What is your technique for freezing fast action without cranking ISO too high?', reactions: ['⚡', '🏃', '📸'] },
  { category: 'technique', text: 'How do you decide when to use a graduated ND filter vs. bracket and blend?', reactions: ['🔲', '📊', '⚖️'] },
  { category: 'technique', text: 'What is your favorite way to create a sense of scale in landscape photos?', reactions: ['🏔️', '🧍', '📸'] },
  { category: 'technique', text: 'How do you handle mixed lighting (e.g. tungsten + daylight) in one frame?', reactions: ['💡', '☀️', '🎨'] },
  { category: 'technique', text: 'What is your sharpening workflow — do you sharpen for screen, print, or both?', reactions: ['🔍', '🖨️', '🖥️'] },
  { category: 'technique', text: 'How do you use the rule of odds in your compositions?', reactions: ['3️⃣', '📐', '🤔'] },
  { category: 'technique', text: 'What is your approach to shooting through foreground elements for depth?', reactions: ['🌿', '🔍', '🖼️'] },
  { category: 'technique', text: 'How do you expose for snow or sand without blowing highlights?', reactions: ['❄️', '🏖️', '📊'] },
  { category: 'technique', text: 'What is the hardest lighting scenario you have photographed, and what did you learn?', reactions: ['💡', '🎓', '💪'] },
  { category: 'technique', text: 'How do you approach dodging and burning — subtle or dramatic?', reactions: ['🖌️', '⚖️', '🎨'] },
  { category: 'technique', text: 'What is your technique for capturing star trails or the Milky Way?', reactions: ['⭐', '🌌', '📸'] },
  { category: 'technique', text: 'How do you use framing elements (doorways, arches, branches) in your photos?', reactions: ['🚪', '🖼️', '📸'] },
  { category: 'technique', text: 'What is the most important thing you check before pressing the shutter?', reactions: ['✅', '📸', '🤔'] },
  { category: 'technique', text: 'How do you deal with lens flare — avoid it or embrace it?', reactions: ['☀️', '✨', '⚖️'] },
  { category: 'technique', text: 'What is your method for getting consistent colors across a photo series?', reactions: ['🎨', '🔗', '📸'] },
  { category: 'technique', text: 'How do you approach high-key vs. low-key lighting for mood?', reactions: ['⬜', '⬛', '🎭'] },
  { category: 'technique', text: 'What is your favorite post-processing trick that most people overlook?', reactions: ['🖥️', '💎', '🤫'] },
  { category: 'technique', text: 'How do you photograph glass or reflective surfaces without unwanted reflections?', reactions: ['🪟', '🔍', '🔧'] },
  { category: 'technique', text: 'What is your approach to shooting during blue hour vs. golden hour?', reactions: ['🔵', '🟡', '⚖️'] },
  { category: 'technique', text: 'How do you maintain image quality when cropping heavily in post?', reactions: ['✂️', '🔍', '📸'] },
  { category: 'technique', text: 'What is your go-to technique for photographing moving water?', reactions: ['🌊', '⏱️', '📸'] },
  { category: 'technique', text: 'How do you use texture as a primary compositional element?', reactions: ['🧱', '🖼️', '🎨'] },
  { category: 'technique', text: 'What is your strategy for shooting in rain without ruining your gear?', reactions: ['🌧️', '📸', '🛡️'] },
  { category: 'technique', text: 'How do you decide between RAW and JPEG for different situations?', reactions: ['📁', '⚖️', '🤔'] },
  { category: 'technique', text: 'What is the most dramatic before/after edit you have done?', reactions: ['🔄', '✨', '🤯'] },
  { category: 'technique', text: 'How do you use symmetry and patterns without making the image feel static?', reactions: ['🔲', '🎨', '💡'] },
  { category: 'technique', text: 'What is your approach to shooting portraits in direct sunlight?', reactions: ['☀️', '🧑', '📸'] },
  { category: 'technique', text: 'How do you calibrate your monitor for accurate color editing?', reactions: ['🖥️', '🎨', '🔧'] },

  // --- gear (11) ---
  { category: 'gear', text: "What's the one piece of gear (besides your camera) you never leave home without?", reactions: ['🎒', '⭐', '📸'] },
  { category: 'gear', text: 'If you could only shoot with one focal length for a year, what would you choose and why?', reactions: ['🔭', '📏', '🤔'] },
  { category: 'gear', text: "What's the best budget photography accessory you've ever bought?", reactions: ['💰', '🏆', '🛒'] },
  { category: 'gear', text: 'Tripod or no tripod — when do you insist on using one?', reactions: ['📐', '🖐️', '⚖️'] },
  { category: 'gear', text: "What software or app has most improved your workflow this year?", reactions: ['💻', '📱', '🚀'] },
  { category: 'gear', text: 'Do you use filters (ND, polarizer, etc.) regularly? Which ones and when?', reactions: ['🔲', '🌊', '🏔️'] },
  { category: 'gear', text: "What's a piece of gear you bought that turned out to be a waste of money?", reactions: ['💸', '😅', '🗑️'] },
  { category: 'gear', text: 'Prime vs. zoom — what is your philosophy and has it changed over time?', reactions: ['🔍', '🔭', '🔄'] },
  { category: 'gear', text: "How do you organize and back up your photo library?", reactions: ['💾', '📂', '☁️'] },
  { category: 'gear', text: "What camera bag setup are you currently using and what would you change?", reactions: ['🎒', '📦', '✏️'] },
  { category: 'gear', text: 'Have you tried any AI-powered editing tools? What do you think of them?', reactions: ['🤖', '🖌️', '👍'] },
  { category: 'gear', text: 'What is the oldest piece of gear you still use regularly and why?', reactions: ['🕰️', '📸', '❤️'] },
  { category: 'gear', text: 'Do you prefer optical or electronic viewfinders? What is the dealbreaker for you?', reactions: ['👁️', '🖥️', '⚖️'] },
  { category: 'gear', text: 'What lens do you reach for first when you walk out the door?', reactions: ['🔭', '🚪', '📸'] },
  { category: 'gear', text: 'How important is weather sealing to you, and has it ever saved a shoot?', reactions: ['🌧️', '🛡️', '📸'] },
  { category: 'gear', text: 'What is your favorite free tool or plugin for photo editing?', reactions: ['🆓', '🖥️', '⭐'] },
  { category: 'gear', text: 'Do you use a color checker or gray card? How has it changed your results?', reactions: ['🎨', '📊', '✅'] },
  { category: 'gear', text: 'What is the best lighting modifier for the price in your experience?', reactions: ['💡', '💰', '🏆'] },
  { category: 'gear', text: 'How many memory cards do you carry and what is your backup strategy on location?', reactions: ['💾', '🎒', '🔄'] },
  { category: 'gear', text: 'Have you switched camera systems? What drove the decision and was it worth it?', reactions: ['🔄', '📸', '🤔'] },
  { category: 'gear', text: 'What is your monitor or display of choice for editing, and why?', reactions: ['🖥️', '🎨', '💰'] },
  { category: 'gear', text: 'Do you use a drone for photography? What has it added to your work?', reactions: ['🚁', '🏔️', '📸'] },
  { category: 'gear', text: 'What is the heaviest kit you have carried for a shoot, and was the result worth the weight?', reactions: ['🏋️', '📸', '⚖️'] },
  { category: 'gear', text: 'Mirrorless or DSLR — have you made the switch, and what do you miss (if anything)?', reactions: ['📸', '🔄', '🤔'] },
  { category: 'gear', text: 'What is the smallest camera setup you own that still produces great results?', reactions: ['📱', '🤏', '⭐'] },
  { category: 'gear', text: 'How do you clean your sensor, and how often?', reactions: ['🧹', '📸', '⏱️'] },
  { category: 'gear', text: 'What is your preferred remote trigger or intervalometer?', reactions: ['🔘', '⏱️', '📸'] },
  { category: 'gear', text: 'Do you print your photos? What printer or service do you use?', reactions: ['🖨️', '🖼️', '⭐'] },
  { category: 'gear', text: 'What is the most overrated piece of photography gear in your opinion?', reactions: ['😬', '💸', '🤷'] },
  { category: 'gear', text: 'How do you choose between different tripod heads (ball, gimbal, pan-tilt)?', reactions: ['📐', '🔄', '🤔'] },
  { category: 'gear', text: 'What gear do you wish existed but nobody makes?', reactions: ['💭', '🔧', '🚀'] },
  { category: 'gear', text: 'Do you use a light meter app on your phone? How does it compare to a dedicated meter?', reactions: ['📱', '📊', '⚖️'] },
  { category: 'gear', text: 'What is the best photography-related purchase you made under $50?', reactions: ['💰', '🏆', '🤑'] },
  { category: 'gear', text: 'How do you protect your gear when shooting in extreme cold?', reactions: ['❄️', '🛡️', '📸'] },
  { category: 'gear', text: 'What external hard drive or NAS setup do you use for your photo archive?', reactions: ['💾', '🏠', '📂'] },
  { category: 'gear', text: 'Do you use lens hoods? When do you take them off?', reactions: ['🔭', '☀️', '🤔'] },
  { category: 'gear', text: 'What is your go-to speedlight or strobe, and what made you pick it?', reactions: ['⚡', '💡', '📸'] },
  { category: 'gear', text: 'How often do you update your camera body vs. investing in new lenses?', reactions: ['📸', '🔭', '⚖️'] },
  { category: 'gear', text: 'What photography gadget looked gimmicky but actually turned out to be useful?', reactions: ['🤷', '🔧', '🏆'] },
  { category: 'gear', text: 'What is your experience with vintage or adapted lenses on modern cameras?', reactions: ['🕰️', '🔭', '📸'] },
  { category: 'gear', text: 'Do you carry a dedicated camera everywhere, or does your phone handle casual shots?', reactions: ['📸', '📱', '⚖️'] },
  { category: 'gear', text: 'What is the longest you have owned a single camera body, and what made you finally upgrade?', reactions: ['⏱️', '📸', '🔄'] },
  { category: 'gear', text: 'How do you manage cable clutter in your studio or editing desk?', reactions: ['🔌', '🧹', '🏠'] },
  { category: 'gear', text: 'What is your favorite tethering setup for studio work?', reactions: ['🔗', '💻', '📸'] },
  { category: 'gear', text: 'Do you use a separate GPS logger or geotagging device when traveling?', reactions: ['📍', '🌍', '📸'] },
  { category: 'gear', text: 'What is the best third-party lens you have used?', reactions: ['🔭', '⭐', '💰'] },
  { category: 'gear', text: 'How do you handle condensation when moving gear between temperature extremes?', reactions: ['💧', '🌡️', '🛡️'] },
  { category: 'gear', text: 'What power bank or battery strategy do you rely on for long shoots?', reactions: ['🔋', '⏱️', '📸'] },
  { category: 'gear', text: 'What is the best reflector hack you have tried on a budget?', reactions: ['💡', '💰', '🔧'] },

  // --- creative (11) ---
  { category: 'creative', text: 'How do you push through a creative rut when nothing feels inspiring?', reactions: ['🧠', '💪', '🌟'] },
  { category: 'creative', text: "What other art form influences your photography the most?", reactions: ['🎨', '🎵', '📖'] },
  { category: 'creative', text: "How do you find your personal style and keep it evolving?", reactions: ['🔍', '🎭', '📈'] },
  { category: 'creative', text: 'Do you plan your shoots in advance or prefer spontaneous discovery?', reactions: ['📋', '🎲', '⚖️'] },
  { category: 'creative', text: "What's a project or series you've been wanting to start but haven't yet? What's holding you back?", reactions: ['💭', '🚧', '🚀'] },
  { category: 'creative', text: 'How do you balance shooting for yourself vs. shooting what gets engagement?', reactions: ['❤️', '📊', '🤔'] },
  { category: 'creative', text: "What's the most meaningful feedback you've ever received on your work?", reactions: ['💬', '💡', '🙏'] },
  { category: 'creative', text: 'Do you keep a photography journal or sketchbook? How does it help your process?', reactions: ['📓', '✏️', '💡'] },
  { category: 'creative', text: "What emotion or feeling do you most want your photos to evoke?", reactions: ['😊', '😢', '😮'] },
  { category: 'creative', text: 'How do you decide when a photo is "done" in post-processing?', reactions: ['✅', '🖥️', '🤔'] },
  { category: 'creative', text: "Has your 'why' for photography changed since you started?", reactions: ['💭', '🔄', '❤️'] },
  { category: 'creative', text: 'Do you ever revisit old photos and re-edit them with fresh eyes? What changes?', reactions: ['🔄', '👁️', '🖥️'] },
  { category: 'creative', text: 'How do you handle creative envy when you see work that is better than yours?', reactions: ['😔', '💪', '🔄'] },
  { category: 'creative', text: 'What is the longest personal project you have worked on, and is it finished?', reactions: ['⏱️', '📸', '🏁'] },
  { category: 'creative', text: 'Do you give your photos titles? How do you come up with them?', reactions: ['📝', '🤔', '🎨'] },
  { category: 'creative', text: 'How do you choose which photos to share publicly and which to keep private?', reactions: ['🌍', '🔒', '⚖️'] },
  { category: 'creative', text: 'What is a creative constraint you have imposed on yourself that produced great results?', reactions: ['🔗', '✨', '💡'] },
  { category: 'creative', text: 'Do you shoot for specific themes, or do themes emerge after the fact?', reactions: ['📋', '🎲', '🤔'] },
  { category: 'creative', text: 'How has your relationship with social media affected your creative output?', reactions: ['📱', '🎨', '⚖️'] },
  { category: 'creative', text: 'What is the most unexpected compliment you have received on a photo?', reactions: ['😊', '💬', '🤯'] },
  { category: 'creative', text: 'Do you collaborate with other photographers? What does that look like?', reactions: ['🤝', '📸', '💡'] },
  { category: 'creative', text: 'How do you stay motivated when nobody seems to notice your work?', reactions: ['💪', '😔', '🌟'] },
  { category: 'creative', text: 'What is one photo you took that changed the direction of your work?', reactions: ['📸', '🔄', '💡'] },
  { category: 'creative', text: 'How do you warm up creatively before an important shoot?', reactions: ['🔥', '🧠', '📸'] },
  { category: 'creative', text: 'Do you curate your portfolio ruthlessly, or keep everything? What is your editing philosophy?', reactions: ['✂️', '📂', '⚖️'] },
  { category: 'creative', text: 'How do you photograph a subject that has been shot millions of times and still make it feel fresh?', reactions: ['🔄', '✨', '💡'] },
  { category: 'creative', text: 'What is the role of imperfection in your work — do you embrace or eliminate it?', reactions: ['🎭', '✨', '⚖️'] },
  { category: 'creative', text: 'How do you decide between a single hero shot and a multi-image series?', reactions: ['1️⃣', '📖', '🤔'] },
  { category: 'creative', text: 'What was a creative risk you took that paid off?', reactions: ['🎲', '🏆', '💪'] },
  { category: 'creative', text: 'Do you ever photograph with no intention of sharing the results? How does that change your approach?', reactions: ['🔒', '🎨', '🧘'] },
  { category: 'creative', text: 'What music, podcast, or audiobook do you listen to while editing?', reactions: ['🎵', '🎧', '🖥️'] },
  { category: 'creative', text: 'How do you handle a shoot that did not go as planned — do you salvage or reshoot?', reactions: ['😬', '🔄', '💪'] },
  { category: 'creative', text: 'What is the most personal photo you have ever taken?', reactions: ['❤️', '📸', '🥺'] },
  { category: 'creative', text: 'How do you develop a consistent color palette across your body of work?', reactions: ['🎨', '🔗', '📸'] },
  { category: 'creative', text: 'Do you prefer to photograph people, places, or objects — and what draws you to that?', reactions: ['🧑', '🏔️', '🎁'] },
  { category: 'creative', text: 'What is a creative habit you practice daily or weekly?', reactions: ['📅', '🧠', '📸'] },
  { category: 'creative', text: 'How do you balance technical mastery with raw creative expression?', reactions: ['⚙️', '🎨', '⚖️'] },
  { category: 'creative', text: 'What does your ideal creative day look like from start to finish?', reactions: ['☀️', '📸', '🌙'] },
  { category: 'creative', text: 'Have you ever abandoned a project midway? What happened?', reactions: ['🚧', '😔', '🤔'] },
  { category: 'creative', text: 'What is the difference between a good photo and a great photo, in your opinion?', reactions: ['⭐', '🏆', '💡'] },
  { category: 'creative', text: 'How do you use photography to tell stories about your community?', reactions: ['🏘️', '📖', '📸'] },
  { category: 'creative', text: 'What is the strangest place inspiration has struck you?', reactions: ['🤯', '💡', '😂'] },
  { category: 'creative', text: 'How do you handle creative burnout — do you push through or step away?', reactions: ['🔥', '🧘', '⚖️'] },
  { category: 'creative', text: 'What would you photograph if you had unlimited time and budget?', reactions: ['💭', '💰', '🌍'] },
  { category: 'creative', text: 'Do you think limitations (gear, location, time) help or hurt creativity?', reactions: ['🔗', '🎨', '⚖️'] },
  { category: 'creative', text: 'What is a photo you almost deleted but are glad you kept?', reactions: ['🗑️', '❤️', '📸'] },
  { category: 'creative', text: 'How do you decide when a creative project is truly complete?', reactions: ['✅', '🤔', '🏁'] },
  { category: 'creative', text: 'What is the biggest creative lesson you learned the hard way?', reactions: ['🎓', '💪', '💡'] },
  { category: 'creative', text: 'How do you keep your photography feeling playful rather than like a chore?', reactions: ['🎲', '😄', '📸'] },

  // --- challenge (10) ---
  { category: 'challenge', text: 'Challenge: shoot 10 photos using only natural window light this week. Share your favorite!', reactions: ['🪟', '☀️', '📸'] },
  { category: 'challenge', text: 'Challenge: capture a compelling photo where the main subject takes up less than 10% of the frame.', reactions: ['🔍', '🖼️', '🎯'] },
  { category: 'challenge', text: 'Challenge: take a photo that tells a complete story without showing any faces.', reactions: ['📖', '🎭', '📷'] },
  { category: 'challenge', text: "Challenge: photograph something mundane and make it look extraordinary.", reactions: ['🥄', '✨', '🏆'] },
  { category: 'challenge', text: 'Challenge: shoot a series of 3 photos that work together to convey a mood.', reactions: ['🎭', '3️⃣', '🌙'] },
  { category: 'challenge', text: 'Challenge: use only your phone camera for a day and share the best result.', reactions: ['📱', '🏆', '👀'] },
  { category: 'challenge', text: 'Challenge: find and photograph an interesting shadow. Bonus if it tells a story.', reactions: ['🌑', '📸', '⭐'] },
  { category: 'challenge', text: 'Challenge: take a self-portrait without showing your face.', reactions: ['🤳', '🎭', '🔥'] },
  { category: 'challenge', text: 'Challenge: photograph the same subject from 5 different angles. Which works best?', reactions: ['🔄', '5️⃣', '👁️'] },
  { category: 'challenge', text: 'Challenge: capture motion blur intentionally to create an abstract image.', reactions: ['💨', '🎨', '📸'] },
  { category: 'challenge', text: 'Challenge: photograph a color you rarely shoot. Make it the star of the image.', reactions: ['🎨', '🌈', '📸'] },
  { category: 'challenge', text: 'Challenge: take a portrait using only available light from a single window.', reactions: ['🪟', '🧑', '📸'] },
  { category: 'challenge', text: 'Challenge: shoot an entire roll (or 36 frames) without chimping — review only after.', reactions: ['📸', '🙈', '🎲'] },
  { category: 'challenge', text: 'Challenge: create a diptych — two photos that tell a story together.', reactions: ['2️⃣', '📖', '📸'] },
  { category: 'challenge', text: 'Challenge: photograph your neighborhood like a tourist seeing it for the first time.', reactions: ['🏘️', '🧳', '📸'] },
  { category: 'challenge', text: 'Challenge: use a reflective surface (puddle, mirror, chrome) as the main element.', reactions: ['🪞', '🌊', '📸'] },
  { category: 'challenge', text: 'Challenge: shoot only in one square block for an hour. How many compelling images can you find?', reactions: ['🔲', '⏱️', '📸'] },
  { category: 'challenge', text: 'Challenge: take a photo where lines converge to a vanishing point.', reactions: ['📐', '🛤️', '📸'] },
  { category: 'challenge', text: 'Challenge: photograph food in a way that does not look like a typical food photo.', reactions: ['🍳', '🎨', '📸'] },
  { category: 'challenge', text: 'Challenge: find beauty in something broken, worn, or decaying.', reactions: ['🏚️', '✨', '📸'] },
  { category: 'challenge', text: 'Challenge: take a compelling photo in the worst weather you can find.', reactions: ['🌧️', '💪', '📸'] },
  { category: 'challenge', text: 'Challenge: photograph hands at work — cooking, building, playing, writing.', reactions: ['🤲', '🔨', '📸'] },
  { category: 'challenge', text: 'Challenge: create an image using only two colors.', reactions: ['🎨', '2️⃣', '📸'] },
  { category: 'challenge', text: 'Challenge: capture a decisive moment — the split-second that tells the story.', reactions: ['⏱️', '📸', '🎯'] },
  { category: 'challenge', text: 'Challenge: photograph your shadow in a creative way.', reactions: ['🌑', '🤳', '🎨'] },
  { category: 'challenge', text: 'Challenge: take a landscape photo that includes no sky.', reactions: ['🏔️', '🚫', '📸'] },
  { category: 'challenge', text: 'Challenge: capture the feeling of loneliness in a single frame.', reactions: ['🎭', '😔', '📸'] },
  { category: 'challenge', text: 'Challenge: photograph something from directly above (flat lay or birds-eye view).', reactions: ['🔝', '👁️', '📸'] },
  { category: 'challenge', text: 'Challenge: shoot a subject using only backlighting.', reactions: ['☀️', '🎭', '📸'] },
  { category: 'challenge', text: 'Challenge: create a photo that looks like it belongs in a different era.', reactions: ['🕰️', '🎨', '📸'] },
  { category: 'challenge', text: 'Challenge: photograph the same tree across four different times of day.', reactions: ['🌳', '4️⃣', '📸'] },
  { category: 'challenge', text: 'Challenge: take a macro photo of something in your pocket right now.', reactions: ['🔍', '🤏', '📸'] },
  { category: 'challenge', text: 'Challenge: shoot an environmental portrait — show a person in their element.', reactions: ['🧑', '🏠', '📸'] },
  { category: 'challenge', text: 'Challenge: photograph a staircase in the most interesting way you can.', reactions: ['🪜', '🎨', '📸'] },
  { category: 'challenge', text: 'Challenge: capture the feeling of warmth without using warm tones.', reactions: ['🔥', '🔵', '🎭'] },
  { category: 'challenge', text: 'Challenge: take a street photo where geometry dominates the composition.', reactions: ['📐', '🏙️', '📸'] },
  { category: 'challenge', text: 'Challenge: make a boring parking lot look cinematic.', reactions: ['🅿️', '🎬', '📸'] },
  { category: 'challenge', text: 'Challenge: photograph water in three different states — still, flowing, and splashing.', reactions: ['🌊', '3️⃣', '📸'] },
  { category: 'challenge', text: 'Challenge: document one hour of your daily routine in 10 photos.', reactions: ['⏱️', '🔟', '📸'] },
  { category: 'challenge', text: 'Challenge: create an image that is primarily about one single texture.', reactions: ['🧱', '🎨', '📸'] },
  { category: 'challenge', text: 'Challenge: shoot a portrait where the environment tells more of the story than the face.', reactions: ['🧑', '🏔️', '📖'] },
  { category: 'challenge', text: 'Challenge: photograph a pet or animal in a way that shows personality.', reactions: ['🐕', '🎭', '📸'] },
  { category: 'challenge', text: 'Challenge: take the most minimalist photo you can — fewest elements possible.', reactions: ['⬜', '🤏', '📸'] },
  { category: 'challenge', text: 'Challenge: find and capture a natural frame within a frame.', reactions: ['🖼️', '🌿', '📸'] },
  { category: 'challenge', text: 'Challenge: photograph light itself as the subject — not what it illuminates.', reactions: ['💡', '✨', '📸'] },
  { category: 'challenge', text: 'Challenge: create a double exposure (in camera or in post). What story does it tell?', reactions: ['🔲', '🎭', '📸'] },
  { category: 'challenge', text: 'Challenge: shoot a self-assigned photo essay with exactly 5 images.', reactions: ['5️⃣', '📖', '📸'] },
  { category: 'challenge', text: 'Challenge: photograph something tiny to make it look monumental.', reactions: ['🤏', '🏔️', '📸'] },
  { category: 'challenge', text: 'Challenge: capture a candid moment of genuine laughter.', reactions: ['😂', '📸', '❤️'] },
  { category: 'challenge', text: 'Challenge: photograph a door or window as the main subject.', reactions: ['🚪', '🪟', '📸'] },
  { category: 'challenge', text: 'Challenge: use only prime lenses (or tape your zoom to one focal length) for a week.', reactions: ['🔭', '📏', '📸'] },
  { category: 'challenge', text: 'Challenge: create an abstract image from an everyday object.', reactions: ['🎨', '🥄', '📸'] },
  { category: 'challenge', text: 'Challenge: photograph a crowd scene where one person stands out.', reactions: ['👥', '🎯', '📸'] },
  { category: 'challenge', text: 'Challenge: shoot a scene that looks completely different in color vs. black and white. Share both.', reactions: ['🎨', '⬛', '📸'] },
  { category: 'challenge', text: 'Challenge: photograph the golden ratio in nature.', reactions: ['🐚', '📐', '📸'] },
  { category: 'challenge', text: 'Challenge: take a photo that makes the viewer feel small.', reactions: ['🏔️', '🧍', '😮'] },
  { category: 'challenge', text: 'Challenge: capture a moment of transition — dawn, dusk, seasons changing, life shifting.', reactions: ['🌅', '🔄', '📸'] },
  { category: 'challenge', text: 'Challenge: photograph a meal from preparation to plate in 5 frames.', reactions: ['🍳', '5️⃣', '📸'] },
  { category: 'challenge', text: 'Challenge: find and capture a juxtaposition — two contrasting elements in one frame.', reactions: ['⚖️', '🎭', '📸'] },

  // --- inspiration (10) ---
  { category: 'inspiration', text: "What photographer's work has had the biggest impact on how you see the world?", reactions: ['👁️', '🌍', '📚'] },
  { category: 'inspiration', text: 'Has a painting, film, or piece of music ever directly inspired a photo you took?', reactions: ['🎨', '🎬', '🎵'] },
  { category: 'inspiration', text: "What's a photography book or documentary you'd recommend to everyone here?", reactions: ['📖', '🎬', '⭐'] },
  { category: 'inspiration', text: 'How does the place you live shape the kind of photos you take?', reactions: ['🏙️', '🌲', '📸'] },
  { category: 'inspiration', text: "What non-photography skill has unexpectedly improved your photos?", reactions: ['🧩', '💡', '📈'] },
  { category: 'inspiration', text: 'Do you look at other photographers\' work for inspiration, or do you avoid it to stay original?', reactions: ['👀', '🚫', '⚖️'] },
  { category: 'inspiration', text: "What's a genre of photography you've never tried but are curious about?", reactions: ['🆕', '🤔', '🎯'] },
  { category: 'inspiration', text: 'If you could photograph any event, place, or person — past or present — what would it be?', reactions: ['🌍', '⏳', '✨'] },
  { category: 'inspiration', text: "How do you use social media as inspiration without falling into comparison?", reactions: ['📱', '⚖️', '💪'] },
  { category: 'inspiration', text: 'What everyday moment recently caught your eye and made you wish you had your camera?', reactions: ['👁️', '📷', '💭'] },
  { category: 'inspiration', text: 'What historical photo has stuck with you the most, and why?', reactions: ['🕰️', '📸', '💭'] },
  { category: 'inspiration', text: 'How does architecture inspire your photography, even when you are not shooting buildings?', reactions: ['🏛️', '📐', '📸'] },
  { category: 'inspiration', text: 'What is a photography technique from another era (daguerreotype, Polaroid, etc.) that inspires your modern work?', reactions: ['🕰️', '📸', '🎨'] },
  { category: 'inspiration', text: 'Who is a non-photographer creative (filmmaker, painter, writer) whose work influences your eye?', reactions: ['🎬', '🎨', '📖'] },
  { category: 'inspiration', text: 'What natural phenomenon (aurora, lightning, fog, etc.) most inspires you to pick up the camera?', reactions: ['🌌', '⚡', '📸'] },
  { category: 'inspiration', text: 'How has travel changed the way you photograph your own home?', reactions: ['✈️', '🏠', '👁️'] },
  { category: 'inspiration', text: 'What is a photo from this community that recently impressed you and why?', reactions: ['🏆', '❤️', '📸'] },
  { category: 'inspiration', text: 'How does the season or weather affect what you want to photograph?', reactions: ['🌦️', '🍂', '📸'] },
  { category: 'inspiration', text: 'What YouTube channel or online resource has taught you the most about photography?', reactions: ['📺', '🎓', '📸'] },
  { category: 'inspiration', text: 'What is a photo exhibition or gallery show that left a lasting impression on you?', reactions: ['🖼️', '🏛️', '✨'] },
  { category: 'inspiration', text: 'How does cooking, gardening, or another hands-on hobby connect to your photography practice?', reactions: ['🍳', '🌱', '📸'] },
  { category: 'inspiration', text: 'What era of photography (1920s street, 1970s color, etc.) do you find most visually compelling?', reactions: ['🕰️', '🎨', '📸'] },
  { category: 'inspiration', text: 'How do you find new locations to photograph in an area you already know well?', reactions: ['🗺️', '🔍', '📸'] },
  { category: 'inspiration', text: 'What poem, song lyric, or quote captures what photography means to you?', reactions: ['📝', '🎵', '❤️'] },
  { category: 'inspiration', text: 'How has becoming a photographer changed the way you experience everyday life?', reactions: ['👁️', '🌍', '🔄'] },
  { category: 'inspiration', text: 'What is a photo assignment or brief you received that pushed you in an unexpected direction?', reactions: ['📋', '🔄', '💡'] },
  { category: 'inspiration', text: 'What children or street photographer do you admire for capturing authentic moments?', reactions: ['👶', '🏙️', '📸'] },
  { category: 'inspiration', text: 'How do dreams, memories, or imagination feed into the images you create?', reactions: ['💭', '🧠', '📸'] },
  { category: 'inspiration', text: 'What is a photo from history that you wish you had taken yourself?', reactions: ['🕰️', '📸', '🤩'] },
  { category: 'inspiration', text: 'How has teaching or mentoring other photographers changed your own perspective?', reactions: ['🎓', '🤝', '💡'] },
  { category: 'inspiration', text: 'What is a cultural tradition or festival that you would love to photograph?', reactions: ['🎭', '🌍', '📸'] },
  { category: 'inspiration', text: 'How does typography, graphic design, or visual branding influence your compositional choices?', reactions: ['🔤', '🎨', '📐'] },
  { category: 'inspiration', text: 'What is the most inspiring photography Instagram account you follow right now?', reactions: ['📱', '⭐', '📸'] },
  { category: 'inspiration', text: 'How has a personal life event changed the subjects or themes you are drawn to?', reactions: ['❤️', '🔄', '📸'] },
  { category: 'inspiration', text: 'What wildlife or nature documentary has made you want to pick up the camera?', reactions: ['🦁', '🎬', '📸'] },
  { category: 'inspiration', text: 'How do you translate an emotion into a visual composition?', reactions: ['🎭', '📐', '💡'] },
  { category: 'inspiration', text: 'What is a photography competition or award that you follow for inspiration?', reactions: ['🏆', '📸', '⭐'] },
  { category: 'inspiration', text: 'How has a failure or rejected photo led to something better?', reactions: ['❌', '🔄', '🏆'] },
  { category: 'inspiration', text: 'What is the most beautiful light you have ever witnessed, photographed or not?', reactions: ['✨', '☀️', '😮'] },
  { category: 'inspiration', text: 'How do street art, murals, or graffiti in your city inspire your photography?', reactions: ['🎨', '🏙️', '📸'] },
  { category: 'inspiration', text: 'What is a subculture or community you would love to document through photos?', reactions: ['👥', '📖', '📸'] },
  { category: 'inspiration', text: 'How has visiting a museum or art gallery directly affected your next shoot?', reactions: ['🏛️', '🎨', '📸'] },
  { category: 'inspiration', text: 'What is the most moving use of photography you have seen outside of fine art (journalism, science, medicine)?', reactions: ['📰', '🔬', '❤️'] },
  { category: 'inspiration', text: 'How does silence, solitude, or stillness play a role in your creative process?', reactions: ['🤫', '🧘', '📸'] },
  { category: 'inspiration', text: 'What is a place you have photographed that felt like it was made for the camera?', reactions: ['🌍', '📸', '✨'] },
  { category: 'inspiration', text: 'How has learning about art history changed how you compose your photographs?', reactions: ['📚', '🎨', '📐'] },
  { category: 'inspiration', text: 'What is a photo project by someone else that you wish you had thought of first?', reactions: ['💭', '🤩', '📸'] },
  { category: 'inspiration', text: 'How do you draw creative energy from a bad day or a difficult experience?', reactions: ['😔', '🔄', '🎨'] },
  { category: 'inspiration', text: 'What photography podcast has given you the best creative advice?', reactions: ['🎙️', '💡', '📸'] },
];
