#!/bin/bash
set -e

# ============================================
# Photobot — First-Time Setup
# ============================================
# Interactive script that walks you through
# initial configuration. Run once after cloning.
#
# Usage:  pnpm init:local
#         ./scripts/setup.sh
# ============================================

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT_DIR"

export DATABASE_URL="${DATABASE_URL:-postgresql://postgres:postgres@localhost:54422/postgres}"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m'

log()  { echo -e "${CYAN}[setup]${NC} $1"; }
ok()   { echo -e "${GREEN}[setup]${NC} $1"; }
warn() { echo -e "${YELLOW}[setup]${NC} $1"; }
fail() { echo -e "${RED}[setup]${NC} $1"; exit 1; }
ask()  { echo -e -n "${BOLD}$1${NC} "; }

echo ""
echo -e "${BOLD}========================================${NC}"
echo -e "${BOLD}  Photobot — First-Time Setup${NC}"
echo -e "${BOLD}========================================${NC}"
echo ""

# -----------------------------------------------
# 1. Check prerequisites
# -----------------------------------------------
log "Checking prerequisites..."

MISSING=()
command -v node   >/dev/null 2>&1 || MISSING+=("node")
command -v pnpm   >/dev/null 2>&1 || MISSING+=("pnpm")
command -v docker >/dev/null 2>&1 || MISSING+=("docker")
command -v git    >/dev/null 2>&1 || MISSING+=("git")

if [ ${#MISSING[@]} -gt 0 ]; then
  fail "Missing required tools: ${MISSING[*]}\nInstall them and re-run this script."
fi

NODE_MAJOR=$(node -v | cut -d. -f1 | tr -d 'v')
if [ "$NODE_MAJOR" -lt 20 ]; then
  fail "Node.js 20+ required (found $(node -v))"
fi

ok "All prerequisites installed"

# -----------------------------------------------
# 2. Configure .env
# -----------------------------------------------
echo ""
if [ -f ".env" ]; then
  ask "A .env file already exists. Overwrite? [y/N]"
  read -r OVERWRITE
  if [ "$OVERWRITE" != "y" ] && [ "$OVERWRITE" != "Y" ]; then
    log "Keeping existing .env"
    SKIP_ENV=true
  fi
fi

if [ "$SKIP_ENV" != "true" ]; then
  echo ""
  echo -e "${BOLD}Discord Configuration${NC}"
  echo "Create an app at https://discord.com/developers/applications"
  echo ""

  ask "Discord Bot Token (DISCORD_TOKEN):"
  read -r DISCORD_TOKEN

  ask "Discord Client ID (Application ID):"
  read -r DISCORD_CLIENT_ID

  ask "Discord Client Secret:"
  read -r DISCORD_CLIENT_SECRET

  echo ""
  echo -e "${BOLD}AI Provider${NC}"
  echo "  1) Ollama (local, free — requires Docker, ~4.7GB download)"
  echo "  2) Gemini (cloud — requires API key)"
  ask "Choose [1/2, default: 1]:"
  read -r AI_CHOICE

  GEMINI_API_KEY=""
  AI_PROVIDER="ollama"
  if [ "$AI_CHOICE" = "2" ]; then
    AI_PROVIDER="gemini"
    ask "Gemini API Key:"
    read -r GEMINI_API_KEY
  fi

  # Generate NEXTAUTH_SECRET
  if command -v openssl >/dev/null 2>&1; then
    NEXTAUTH_SECRET=$(openssl rand -base64 32)
  else
    NEXTAUTH_SECRET=$(head -c 32 /dev/urandom | base64)
  fi

  log "Writing .env..."
  cat > .env << EOF
# ======================
# Photobot Environment Variables
# Generated by scripts/setup.sh
# ======================

# --- Discord ---
DISCORD_TOKEN=${DISCORD_TOKEN}
DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
DISCORD_CLIENT_SECRET=${DISCORD_CLIENT_SECRET}

# --- Database ---
DATABASE_URL=postgresql://postgres:postgres@localhost:54422/postgres

# --- NextAuth (Dashboard) ---
NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
NEXTAUTH_URL=http://localhost:3100

# --- Supabase (local Docker) ---
NEXT_PUBLIC_SUPABASE_URL=http://localhost:54421
NEXT_PUBLIC_SUPABASE_ANON_KEY=placeholder-for-local-dev
SUPABASE_SERVICE_ROLE_KEY=placeholder-for-local-dev

# --- AI Provider ---
AI_PROVIDER=${AI_PROVIDER}
OLLAMA_HOST=http://localhost:11434
GEMINI_API_KEY=${GEMINI_API_KEY}
EOF

  ok ".env created with auto-generated NEXTAUTH_SECRET"
fi

# -----------------------------------------------
# 3. Install dependencies
# -----------------------------------------------
echo ""
log "Installing dependencies..."
pnpm install
ok "Dependencies installed"

# -----------------------------------------------
# 4. Start Docker and set up database
# -----------------------------------------------
echo ""
ask "Start Docker services and set up database now? [Y/n]"
read -r START_DOCKER

if [ "$START_DOCKER" != "n" ] && [ "$START_DOCKER" != "N" ]; then
  docker info >/dev/null 2>&1 || fail "Docker daemon is not running. Start Docker and re-run."

  log "Starting Docker services..."
  docker compose up -d

  log "Waiting for database..."
  MAX_RETRIES=30
  RETRY_COUNT=0
  until [ "$(docker inspect -f '{{.State.Health.Status}}' photobot-db 2>/dev/null)" = "healthy" ]; do
    if [ $RETRY_COUNT -ge $MAX_RETRIES ]; then
      fail "Database did not become healthy within 60 seconds."
    fi
    printf "."
    sleep 2
    RETRY_COUNT=$((RETRY_COUNT + 1))
  done
  echo ""
  ok "Database is healthy"

  sleep 2
  log "Setting up database schema..."
  pnpm -C packages/db exec prisma generate --no-hints
  pnpm -C packages/db exec prisma db push --skip-generate
  ok "Database schema applied"

  # Pull Ollama model if using Ollama
  if [ "$AI_PROVIDER" = "ollama" ]; then
    if docker ps --format '{{.Names}}' | grep -q photography-bot-ollama; then
      log "Pulling Ollama llava model (this takes a few minutes on first run)..."
      docker exec photography-bot-ollama ollama pull llava
      ok "Ollama model ready"
    fi
  fi
fi

# -----------------------------------------------
# 5. Build shared packages
# -----------------------------------------------
echo ""
log "Building shared packages..."
pnpm -C packages/db build 2>/dev/null
pnpm -C packages/ai build 2>/dev/null
ok "Shared packages built"

# -----------------------------------------------
# Done
# -----------------------------------------------
echo ""
echo -e "${BOLD}========================================${NC}"
echo -e "${GREEN}  Setup complete!${NC}"
echo -e "${BOLD}========================================${NC}"
echo ""
echo "  Next steps:"
echo ""
echo "    1. Add Discord OAuth redirect URL:"
echo "       https://discord.com/developers/applications/${DISCORD_CLIENT_ID}/oauth2"
echo "       Add: http://localhost:3100/api/auth/callback/discord"
echo ""
echo "    2. Invite the bot to a test server:"
echo "       https://discord.com/developers/applications/${DISCORD_CLIENT_ID}/oauth2"
echo "       Scopes: bot, applications.commands"
echo "       Permissions: Send Messages, Create Public Threads,"
echo "                    Add Reactions, Attach Files, Use Slash Commands"
echo ""
echo "    3. Start developing:"
echo -e "       ${CYAN}pnpm dev:local${NC}   # Full stack (Docker + apps)"
echo -e "       ${CYAN}pnpm dev${NC}         # Apps only (Docker already running)"
echo -e "       ${CYAN}pnpm status${NC}      # Check health of all services"
echo ""
echo "  Available bot commands: /critique, /palette, /discuss, /settings"
echo "  Dashboard: http://localhost:3100"
echo "  Full guide: docs/GETTING_STARTED.md"
echo ""
